### ISSUE TITLE
MacOS prefix builds aren't guaranteed portable between MacOS (major) versions...

### ISSUE THREAD

**Issue by terjekv** [EESSI/compatibility-layer#62]
A fairly trivial test:
```
terjekv@minbar:~/projects/eessi$ ls -lad ~/Gentoo
lrwxr-xr-x 1 terjekv 11 des  4 18:08 /Users/terjekv/Gentoo -> Gentoo-11.0/
terjekv@minbar:~/projects/eessi$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2
terjekv@minbar:~/projects/eessi$ git clone git@github.com:EESSI/compatibility-layer.git
Cloning into 'compatibility-layer'...
dyld: lazy symbol binding failed: Symbol not found: _strtonum
  Referenced from: /Users/terjekv/Gentoo/usr/bin/ssh (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _strtonum
  Referenced from: /Users/terjekv/Gentoo/usr/bin/ssh (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by boegel** [comment]
I wouldn't expect this (running software on macOS 10.15 that was built for macOS 11.0) to work, tbh.

What about the other way around though (build on 10.15, run on 11.0), does that work?

**Comment by terjekv** [comment]
Running the 10.15 x86_64 prefix on 11.0 seems to work fine!
